import { StatusBar } from 'expo-status-bar';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
import * as FileSystem from 'expo-file-system/legacy';
import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { supabase } from './src/lib/supabase';
import Rides from './src/Rides';

const FAST_EMAIL_DOMAINS = ['lhr.nu.edu.pk', 'nu.edu.pk'];
const ADMIN_USER_ID = process.env.EXPO_PUBLIC_ADMIN_USER_ID ?? '00000000-0000-0000-0000-000000000000';
const isFastEmail = (email: string) => FAST_EMAIL_DOMAINS.includes(email.trim().toLowerCase().split('@')[1] ?? '');
type Profile = { id: string; full_name: string; batch: string; gender: string; phone: string; fast_id_status: 'pending' | 'verified' | 'rejected' };

export default function App() {
  const [session, setSession] = useState<any>(null); const [profile, setProfile] = useState<Profile | null>(null); const [mode, setMode] = useState<'signIn' | 'signUp'>('signIn'); const [screen, setScreen] = useState<'auth' | 'onboarding' | 'status' | 'admin'>('auth'); const [loading, setLoading] = useState(true); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [batch, setBatch] = useState(''); const [gender, setGender] = useState(''); const [phone, setPhone] = useState(''); const [image, setImage] = useState<ImagePicker.ImagePickerAsset | null>(null); const [submitting, setSubmitting] = useState(false); const [pending, setPending] = useState<any[]>([]);
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); if (data.session) loadProfile(data.session.user.id); else setLoading(false); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => { setSession(next); if (next) loadProfile(next.user.id); else { setProfile(null); setScreen('auth'); } }); return () => listener.subscription.unsubscribe(); }, []);
  async function loadProfile(userId: string) { setLoading(true); const { data } = await supabase.from('profiles').select('*').eq('id', userId).maybeSingle(); setProfile(data); setScreen(data ? 'status' : 'onboarding'); setLoading(false); }
  async function authenticate() { if (!email || !password) return Alert.alert('Missing details', 'Enter your FAST email and password.'); if (!isFastEmail(email)) return Alert.alert('FAST email required', 'Use your FAST Lahore student email, for example name@lhr.nu.edu.pk.'); setSubmitting(true); const result = mode === 'signUp' ? await supabase.auth.signUp({ email: email.trim().toLowerCase(), password }) : await supabase.auth.signInWithPassword({ email: email.trim().toLowerCase(), password }); setSubmitting(false); if (result.error) return Alert.alert('Could not continue', result.error.message); if (mode === 'signUp' && !result.data.session) Alert.alert('Check your inbox', 'Confirm your FAST email, then return here to sign in.'); }
  async function chooseImage(source: 'camera' | 'gallery') { const result = source === 'camera' ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 1 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 1 }); if (result.canceled) return; setSubmitting(true); try { const original = result.assets[0]; const scales = [1000, 800, 650, 500]; const qualities = [0.55, 0.45, 0.35, 0.28]; let compressed: any = null; for (let i=0;i<scales.length;i++) { const longest = Math.max(original.width, original.height); const resize = longest > scales[i] ? { resize: { width: original.width >= original.height ? scales[i] : Math.round(original.width * scales[i] / original.height) } } : {}; const out = await ImageManipulator.manipulateAsync(original.uri, resize as any, { compress: qualities[i], format: ImageManipulator.SaveFormat.JPEG }); const info = await FileSystem.getInfoAsync(out.uri); if (info.exists && info.size <= 51200) { compressed = { ...original, uri: out.uri, fileSize: info.size, mimeType: 'image/jpeg' }; break; } } if (!compressed) Alert.alert('Photo is too large', 'We could not get this image under 50 KB while keeping it readable. Retake it in better lighting or at a lower resolution.'); else setImage(compressed); } catch { Alert.alert('Photo processing failed', 'Retake the card photo in better lighting or choose a smaller image.'); } finally { setSubmitting(false); } }
  async function submitOnboarding() { if (!session || !fullName || !batch || !gender || !phone || !image) return Alert.alert('Complete your profile', 'Add every field and a clear photo of your FAST ID card.'); setSubmitting(true); const path = `${session.user.id}/${Date.now()}.jpg`; const file = await (await fetch(image.uri)).arrayBuffer(); const upload = await supabase.storage.from('fast-id-cards').upload(path, file, { contentType: image.mimeType ?? 'image/jpeg', upsert: false }); if (upload.error) { setSubmitting(false); return Alert.alert('Upload failed', upload.error.message); } const { error: profileError } = await supabase.from('profiles').upsert({ id: session.user.id, full_name: fullName.trim(), batch: batch.trim(), gender, phone: phone.trim(), fast_id_status: 'pending' }); const { error: verificationError } = await supabase.from('fast_id_verifications').insert({ user_id: session.user.id, id_card_image_url: path }); if (profileError || verificationError) { await supabase.storage.from('fast-id-cards').remove([path]); setSubmitting(false); return Alert.alert('Could not save profile', (profileError ?? verificationError)?.message); } setProfile({ id: session.user.id, full_name: fullName.trim(), batch: batch.trim(), gender, phone: phone.trim(), fast_id_status: 'pending' }); setSubmitting(false); setScreen('status'); }
  async function loadPending() { const { data, error } = await supabase.from('fast_id_verifications').select('id,user_id,id_card_image_url,submitted_at,profiles(full_name,batch)').eq('status', 'pending').order('submitted_at'); if (error) return Alert.alert('Admin access unavailable', error.message); const withUrls = await Promise.all((data ?? []).map(async (item: any) => ({ ...item, imageUrl: (await supabase.storage.from('fast-id-cards').createSignedUrl(item.id_card_image_url, 300)).data?.signedUrl }))); setPending(withUrls); }
  async function review(item: any, decision: 'verified' | 'rejected') { setSubmitting(true); const removed = await supabase.storage.from('fast-id-cards').remove([item.id_card_image_url]); if (removed.error) { setSubmitting(false); return Alert.alert('Review stopped', 'The image was not deleted, so the result was not saved.'); } const updated = await supabase.from('profiles').update({ fast_id_status: decision }).eq('id', item.user_id); const deleted = await supabase.from('fast_id_verifications').delete().eq('id', item.id); setSubmitting(false); if (updated.error || deleted.error) return Alert.alert('Review incomplete', (updated.error ?? deleted.error)?.message); loadPending(); }
  if (loading) return <Centered text="Loading FAST Carpool…" />; if (!session || screen === 'auth') return <AuthScreen mode={mode} setMode={setMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} onSubmit={authenticate} submitting={submitting} />; if (screen === 'onboarding') return <Onboarding fullName={fullName} setFullName={setFullName} batch={batch} setBatch={setBatch} gender={gender} setGender={setGender} phone={phone} setPhone={setPhone} image={image} chooseImage={chooseImage} submit={submitOnboarding} submitting={submitting} />; if (screen === 'admin') return <AdminScreen pending={pending} review={review} back={() => setScreen('status')} submitting={submitting} />; return <StatusScreen profile={profile} isAdmin={session.user.id === ADMIN_USER_ID} openAdmin={() => { setScreen('admin'); loadPending(); }} signOut={() => supabase.auth.signOut()} />;
}
function AuthScreen(p: any) { return <SafeAreaView style={s.safe}><View style={s.hero}><Text style={s.logo}>FAST<Text style={s.logoAccent}>POOL</Text></Text><Text style={s.tagline}>Ride together. Belong together.</Text></View><View style={s.card}><Text style={s.title}>{p.mode === 'signUp' ? 'Create your account' : 'Welcome back'}</Text><Text style={s.muted}>FAST Lahore students only · {FAST_EMAIL_DOMAINS[0]}</Text><TextInput style={s.input} placeholder="FAST email" autoCapitalize="none" keyboardType="email-address" value={p.email} onChangeText={p.setEmail} /><TextInput style={s.input} placeholder="Password" secureTextEntry value={p.password} onChangeText={p.setPassword} /><Pressable style={s.primary} onPress={p.onSubmit} disabled={p.submitting}><Text style={s.primaryText}>{p.submitting ? 'Please wait…' : p.mode === 'signUp' ? 'Sign up' : 'Sign in'}</Text></Pressable><Pressable onPress={() => p.setMode(p.mode === 'signUp' ? 'signIn' : 'signUp')}><Text style={s.link}>{p.mode === 'signUp' ? 'Already have an account? Sign in' : 'New to FASTPOOL? Create an account'}</Text></Pressable></View><StatusBar style="light" /></SafeAreaView> }
function Onboarding(p: any) { return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll}><Text style={s.eyebrow}>ONE-TIME SETUP</Text><Text style={s.title}>Tell us about you</Text><Text style={s.muted}>Your phone is private and used only for ride coordination.</Text>{[['Full name',p.fullName,p.setFullName],['Batch (e.g. 2026)',p.batch,p.setBatch],['Gender',p.gender,p.setGender],['Phone number',p.phone,p.setPhone]].map(([ph,v,set]: any) => <TextInput key={ph} style={s.input} placeholder={ph} value={v} onChangeText={set} />)}<Text style={s.privacy}><Text style={s.bold}>FAST student card only:</Text> Your card image is only used to confirm you’re a real, enrolled FAST student. It is reviewed once and then deleted, not stored.</Text><View style={s.uploadBox}>{p.image ? <Image source={{ uri: p.image.uri }} style={s.preview} /> : <Text style={s.muted}>No FAST student card selected</Text>}<View style={s.row}><Pressable style={s.secondary} onPress={() => p.chooseImage('camera')}><Text style={s.secondaryText}>Use camera</Text></Pressable><Pressable style={s.secondary} onPress={() => p.chooseImage('gallery')}><Text style={s.secondaryText}>Choose photo</Text></Pressable></View></View><Pressable style={s.primary} onPress={p.submit} disabled={p.submitting}><Text style={s.primaryText}>{p.submitting ? 'Submitting…' : 'Submit for review'}</Text></Pressable></ScrollView></SafeAreaView> }
function StatusScreen({ profile, isAdmin, openAdmin, signOut }: any) { const status = profile?.fast_id_status ?? 'pending'; if (status === 'verified') return <SafeAreaView style={s.safe}><Rides userId={profile.id} gender={profile.gender}/><Pressable onPress={signOut}><Text style={s.link}>Sign out</Text></Pressable></SafeAreaView>; return <SafeAreaView style={s.safe}><View style={s.status}><Text style={s.logo}>FAST<Text style={s.logoAccent}>POOL</Text></Text><View style={s.statusIcon}><Text style={s.statusIconText}>{status === 'rejected' ? '!' : '…'}</Text></View><Text style={s.title}>{status === 'rejected' ? 'Verification rejected' : 'Pending review'}</Text><Text style={s.mutedCenter}>{status === 'rejected' ? 'Please contact an admin if you think this is a mistake.' : 'We’ll review your FAST ID once. Ride posting and requests unlock after approval.'}</Text>{isAdmin && <Pressable style={s.secondary} onPress={openAdmin}><Text style={s.secondaryText}>Open admin review</Text></Pressable>}<Pressable onPress={signOut}><Text style={s.link}>Sign out</Text></Pressable></View></SafeAreaView> }
function AdminScreen({ pending, review, back, submitting }: any) { return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll}><Pressable onPress={back}><Text style={s.link}>← Back</Text></Pressable><Text style={s.title}>ID review queue</Text><Text style={s.muted}>Compare the typed profile details with the FAST student card. The image is deleted automatically after the decision.</Text>{pending.length === 0 ? <Text style={s.muted}>No pending submissions.</Text> : pending.map((item: any) => <View style={s.uploadBox} key={item.id}><View style={{flexDirection:'row',gap:12,alignItems:'flex-start'}}>{item.imageUrl && <Image source={{ uri: item.imageUrl }} style={{width:150,height:110,borderRadius:10}} />}<View style={{flex:1}}><Text style={s.eyebrow}>TYPED PROFILE</Text><Text style={s.bold}>{item.profiles?.full_name ?? item.user_id}</Text><Text style={s.muted}>Batch {item.profiles?.batch ?? '—'}</Text><Text style={s.muted}>Check name and batch against the card.</Text></View></View><Pressable style={s.primary} disabled={submitting} onPress={() => review(item, 'verified')}><Text style={s.primaryText}>Approve</Text></Pressable><Pressable style={s.secondary} disabled={submitting} onPress={() => review(item, 'rejected')}><Text style={s.secondaryText}>Reject</Text></Pressable></View>)}</ScrollView></SafeAreaView> }
function Centered({ text }: { text: string }) { return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.muted}>{text}</Text></View></SafeAreaView> }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#08111f' }, hero: { padding: 32, paddingTop: 70 }, logo: { color: '#fff', fontSize: 42, fontWeight: '900', letterSpacing: -2 }, logoAccent: { color: '#54e1b7' }, tagline: { color: '#a8b5c6', marginTop: 8, fontSize: 16 }, card: { backgroundColor: '#f7fafc', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 28, flex: 1 }, title: { color: '#101b2d', fontSize: 28, fontWeight: '800', marginBottom: 8 }, muted: { color: '#6b7788', lineHeight: 21 }, mutedCenter: { color: '#6b7788', textAlign: 'center', lineHeight: 23, maxWidth: 310 }, input: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#dce3eb', borderRadius: 12, padding: 15, marginTop: 14, fontSize: 16 }, primary: { backgroundColor: '#0f8f72', borderRadius: 12, padding: 16, alignItems: 'center', marginTop: 20 }, primaryText: { color: '#fff', fontWeight: '800', fontSize: 16 }, link: { color: '#54e1b7', textAlign: 'center', marginTop: 20, fontWeight: '700' }, scroll: { padding: 24, paddingTop: 52, backgroundColor: '#f7fafc', flexGrow: 1 }, eyebrow: { color: '#0f8f72', fontWeight: '800', letterSpacing: 1.5, marginBottom: 10 }, uploadBox: { backgroundColor: '#eaf6f2', borderRadius: 16, padding: 16, alignItems: 'center', marginTop: 18 }, preview: { width: '100%', height: 170, borderRadius: 12, marginBottom: 14 }, row: { flexDirection: 'row', gap: 10, marginTop: 14 }, secondary: { borderWidth: 1, borderColor: '#0f8f72', borderRadius: 10, padding: 12, alignItems: 'center', marginTop: 18, flex: 1 }, secondaryText: { color: '#0f8f72', fontWeight: '800' }, privacy: { color: '#556274', lineHeight: 21, marginTop: 20 }, bold: { fontWeight: '800', color: '#243247' }, status: { alignItems: 'center', padding: 28, paddingTop: 80, flex: 1 }, statusIcon: { width: 76, height: 76, borderRadius: 38, backgroundColor: '#183c3b', alignItems: 'center', justifyContent: 'center', marginTop: 65, marginBottom: 24 }, statusIconText: { color: '#54e1b7', fontSize: 34, fontWeight: '800' }, center: { flex: 1, justifyContent: 'center', alignItems: 'center' }, adminHint: { color: '#a8b5c6', textAlign: 'center', marginTop: 30, lineHeight: 20 } });
