import * as Location from 'expo-location';
import * as Notifications from 'expo-notifications';
import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { supabase } from './lib/supabase';

Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldShowAlert: true, shouldShowBanner: true, shouldShowList: true, shouldPlaySound: true, shouldSetBadge: false }) });
type Props = { userId: string; gender: string };
export default function Rides({ userId, gender }: Props) {
  const [tab, setTab] = useState<'find'|'post'|'active'>('find'); const [rides, setRides] = useState<any[]>([]); const [area, setArea] = useState(''); const [departure, setDeparture] = useState(''); const [seats, setSeats] = useState('1'); const [price, setPrice] = useState('0'); const [sameGender, setSameGender] = useState(gender.toLowerCase() === 'female'); const [coords, setCoords] = useState<any>(null); const [requests, setRequests] = useState<any[]>([]); const [active, setActive] = useState<any>(null); const [sharing, setSharing] = useState(false);
  useEffect(() => { registerPush(); locate(); loadRides(); }, []);
  async function registerPush() { const p = await Notifications.requestPermissionsAsync(); if (p.granted) { const token = (await Notifications.getExpoPushTokenAsync()).data; await supabase.from('profiles').update({ push_token: token }).eq('id', userId); } }
  async function locate() { const perm = await Location.requestForegroundPermissionsAsync(); if (perm.granted) { const loc = await Location.getCurrentPositionAsync({}); setCoords(loc.coords); } }
  async function loadRides() { const { data } = await supabase.from('rides').select('*,profiles!rides_driver_id_fkey(full_name,gender)').eq('status','active').order('departure_at'); setRides((data ?? []).sort((a:any,b:any) => distance(a.start_lat,a.start_lng,coords?.latitude,coords?.longitude)-distance(b.start_lat,b.start_lng,coords?.latitude,coords?.longitude))); }
  function distance(a?:number,b?:number,c?:number,d?:number) { if ([a,b,c,d].some(v => v == null)) return 999999; const x=(a!-c!)*111, y=(b!-d!)*111*Math.cos((c!*Math.PI)/180); return Math.sqrt(x*x+y*y); }
  async function gps() { await locate(); }
  async function push(token:string|undefined,title:string,body:string) { if (!token) return; await fetch('https://exp.host/--/api/v2/push/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:token,title,body})}); }
  async function post() { if (!area || !departure || !coords) return Alert.alert('Add ride details','Set an area, departure time, and enable location.'); const when = new Date(departure); const { error } = await supabase.from('rides').insert({ driver_id:userId,start_area:area,start_lat:coords.latitude,start_lng:coords.longitude,departure_at:when.toISOString(),available_seats:Number(seats),price_per_seat:Number(price),gender_pref:sameGender?'same_gender_only':'any' }); if(error) Alert.alert('Could not post',error.message); else { if (when.getTime() > Date.now()) await Notifications.scheduleNotificationAsync({content:{title:'Ride starting soon',body:`Your ride from ${area} is coming up.`},trigger:{type:Notifications.SchedulableTriggerInputTypes.DATE,date:new Date(when.getTime()-30*60*1000)}}); Alert.alert('Ride posted','Verified FAST riders can now request a seat.'); setTab('find'); loadRides(); } }
  async function request(ride:any) { const { error } = await supabase.from('ride_requests').insert({ ride_id:ride.id,rider_id:userId }); if(error) Alert.alert('Request failed',error.message); else { const driver = await supabase.from('profiles').select('push_token').eq('id',ride.driver_id).maybeSingle(); await push(driver.data?.push_token,'New ride request',`Someone requested a seat from ${ride.start_area}.`); Alert.alert('Request sent','The driver will be notified.'); } }
  async function loadDriverRequests() { const { data } = await supabase.from('ride_requests').select('*,rides!inner(id,start_area,departure_at,driver_id,start_lat,start_lng)').eq('rides.driver_id',userId).eq('status','pending'); setRequests(data??[]); const mine = await supabase.from('ride_requests').select('*,rides!inner(id,start_area,departure_at,driver_id,start_lat,start_lng)').eq('rider_id',userId).eq('status','accepted').maybeSingle(); if (mine.data) startSharing(mine.data.rides); }
  async function decide(item:any,status:'accepted'|'rejected') { await supabase.from('ride_requests').update({status}).eq('id',item.id); const rider = await supabase.from('profiles').select('push_token').eq('id',item.rider_id).maybeSingle(); await push(rider.data?.push_token,`Ride request ${status}`,status==='accepted'?`Your ride from ${item.rides.start_area} was accepted.`:`Your request for ${item.rides.start_area} was rejected.`); if (status === 'accepted') startSharing({ ...item.rides, id: item.ride_id }); loadDriverRequests(); }
  async function startSharing(ride:any) { setActive(ride); setSharing(true); await supabase.from('live_locations').upsert({ user_id:userId,ride_id:ride.id,lat:coords?.latitude ?? ride.start_lat,lng:coords?.longitude ?? ride.start_lng }); await Location.watchPositionAsync({ accuracy: Location.Accuracy.Balanced, timeInterval: 10000, distanceInterval: 25 }, async l => { await supabase.from('live_locations').upsert({ user_id:userId,ride_id:ride.id,lat:l.coords.latitude,lng:l.coords.longitude,updated_at:new Date().toISOString() }); }); }
  async function complete(ride:any) { await supabase.from('rides').update({status:'completed'}).eq('id',ride.id); await supabase.from('live_locations').delete().eq('user_id',userId).eq('ride_id',ride.id); setSharing(false); setActive(null); }
  return <View style={r.wrap}><View style={r.tabs}><Pressable onPress={()=>{setTab('find');loadRides();}}><Text style={tab==='find'?r.active:r.tab}>Find a ride</Text></Pressable><Pressable onPress={()=>setTab('post')}><Text style={tab==='post'?r.active:r.tab}>Post a ride</Text></Pressable><Pressable onPress={()=>{setTab('active');loadDriverRequests();}}><Text style={tab==='active'?r.active:r.tab}>Requests</Text></Pressable></View>{tab==='post'&&<ScrollView><Text style={r.heading}>Offer a ride</Text><TextInput style={r.input} placeholder="Starting area (e.g. Johar Town)" value={area} onChangeText={setArea}/><TextInput style={r.input} placeholder="Departure (2026-09-10T18:30)" value={departure} onChangeText={setDeparture}/><View style={r.row}><TextInput style={r.small} placeholder="Seats" keyboardType="number-pad" value={seats} onChangeText={setSeats}/><TextInput style={r.small} placeholder="Price / seat" keyboardType="decimal-pad" value={price} onChangeText={setPrice}/></View><Pressable style={r.gps} onPress={gps}><Text style={r.gpsText}>{coords?'✓ Location captured':'Use current location'}</Text></Pressable><Text style={r.label}>Rider preference</Text><View style={r.row}><Pressable style={!sameGender?r.choice:r.choiceOff} onPress={()=>setSameGender(false)}><Text>Any gender</Text></Pressable><Pressable style={sameGender?r.choice:r.choiceOff} onPress={()=>setSameGender(true)}><Text>Same gender only</Text></Pressable></View><Pressable style={r.primary} onPress={post}><Text style={r.primaryText}>Post ride</Text></Pressable></ScrollView>}{tab==='find'&&<ScrollView><Text style={r.heading}>Nearby rides</Text>{rides.length===0?<Text>No active rides nearby.</Text>:rides.map(x=><View style={r.card} key={x.id}><Text style={r.cardTitle}>{x.start_area}</Text><Text>{new Date(x.departure_at).toLocaleString()} · {x.available_seats} seats · Rs {x.price_per_seat}</Text><Text>{x.gender_pref==='same_gender_only'?'Same-gender riders':'Any gender'} · {x.profiles?.full_name}</Text><Pressable style={r.primary} onPress={()=>request(x)}><Text style={r.primaryText}>Request a seat</Text></Pressable></View>)}</ScrollView>}{tab==='active'&&<ScrollView><Text style={r.heading}>Driver requests</Text>{requests.length===0?<Text>No pending requests.</Text>:requests.map(x=><View style={r.card} key={x.id}><Text style={r.cardTitle}>{x.profiles?.full_name}</Text><Text>{x.rides?.start_area}</Text><View style={r.row}><Pressable style={r.primary} onPress={()=>decide(x,'accepted')}><Text style={r.primaryText}>Accept</Text></Pressable><Pressable style={r.choiceOff} onPress={()=>decide(x,'rejected')}><Text>Reject</Text></Pressable></View></View>)}{active&&<View style={r.card}><Text style={r.cardTitle}>Live location sharing</Text><Text>{sharing?'Sharing your current location for this accepted ride.':'Not sharing'}</Text><Pressable style={r.primary} onPress={()=>complete(active)}><Text style={r.primaryText}>Mark ride completed</Text></Pressable></View>}</ScrollView>}</View>
}
const r=StyleSheet.create({wrap:{flex:1,backgroundColor:'#f7fafc',padding:20},tabs:{flexDirection:'row',justifyContent:'space-between',marginBottom:20},tab:{color:'#718096',fontWeight:'700'},active:{color:'#0f8f72',fontWeight:'900'},heading:{fontSize:26,fontWeight:'800',marginBottom:14},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dce3eb',borderRadius:10,padding:14,marginBottom:12},small:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:'#dce3eb',borderRadius:10,padding:14,marginRight:8},row:{flexDirection:'row',gap:8,alignItems:'center',marginBottom:12},gps:{padding:14,borderRadius:10,backgroundColor:'#e1f5ee'},gpsText:{color:'#0f8f72',fontWeight:'800'},label:{fontWeight:'800',marginTop:8},choice:{flex:1,padding:14,borderRadius:10,backgroundColor:'#bcebdc',alignItems:'center'},choiceOff:{flex:1,padding:14,borderRadius:10,borderWidth:1,borderColor:'#cbd5e0',alignItems:'center'},primary:{backgroundColor:'#0f8f72',padding:14,borderRadius:10,alignItems:'center',marginTop:12,flex:1},primaryText:{color:'#fff',fontWeight:'800'},card:{backgroundColor:'#fff',padding:16,borderRadius:14,marginBottom:12},cardTitle:{fontWeight:'800',fontSize:17,marginBottom:5}});
